security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            entity:
                class: App\Common\Entity\User
                property: '%env(resolve:USER_AUTH_FIELD)%'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            user_checker: App\Common\Security\UserChecker
            pattern: ^/login
            stateless: true
            provider: user_provider
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: '%env(resolve:USER_AUTH_FIELD)%'
                password_path: password

        main:
            user_checker: App\Common\Security\UserChecker
            pattern: ^/
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
