<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'REPEATED_PASSWORD_TTL' => '5',
  'USER_AUTH_FIELD' => 'username',
  'API_TOKEN_HEADER_FIELD_NAME' => 'API-Token',
  'API_PREFIX' => '/api/v1/management-service',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_TTL' => '28800',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'APP_DEBUG' => 'true',
  'API_TOKEN_ENC_KEY' => 'Jj8qq4522n8p46xjElx8JARbsqLtrB9bgtdyUmkcH2Q=',
  'APP_SECRET' => 'wdUfQQqkgn5qgvq65DjVsEaS9EkAZVvN',
  'DATABASE_HOST' => 'hospital-database',
  'DATABASE_PASSWORD' => 'root',
  'DATABASE_PORT' => '5432',
  'DATABASE_SCHEMA' => 'hospital',
  'DATABASE_USER' => 'root',
  'DATABASE_VERSION' => '16',
  'JWT_PASSPHRASE' => 'sNfzG33K8763ZrsCL4sdeeIfRIqnvEVq',
);
