services:
  service-management:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: service-management
    image: service-management-image
    environment:
      - "TZ=Europe/Rome"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-base.ini
    ports:
      - "20001:80"
    restart: unless-stopped
    networks:
      - net_storage

networks:
  net_storage:
    name: net_storage
    external: true

#    networks:
#      - database-main_net_storage
#
#networks:
#  database-main_net_storage:
#    name: database-main_net_storage
#    external: true