services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: management_service
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-base.ini
    ports:
      - "20001:80"
    restart: unless-stopped
