common_controllers:
  prefix: /api/v1/management-service
  resource:
    path: ../../src/Common/Controller/
    namespace: App\Common\Controller
  type: attribute

api_controllers:
  prefix: /api/v1/management-service
  resource:
    path: ../../src/Api/Controller/
    namespace: App\Api\Controller
  type: attribute

kernel:
  resource: ../../src/Kernel.php
  type: attribute